---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: OpIBZWCMN0KumFYQ4m+D9j1o1YQhNNsnYk+JGz/lJvd7ZFrTuGIiJ33RxndeUClGf6eC1MKVTmttZuKjVv7EzFuZKdHBt8+Win9+hEc8QtkUpccoNWI5MfjiVOHpF3OhNwFEJsG0yuR6tF72vjqhQLELuOgeJNts+gnU97kbWp86VrErAz7T+vJR0PEzq67Vv5oB3Fn1HuMN9Lz7a6XZ0uFew6owQmfxkffwnQdEhF3mJ2aFAOgD4/8sH4Tvf1KttC1Ob3/OLTVECsP2rEMnCC9nZEs4Qu4Fqs5ZQQVBHwm/GbZYnnkUp2JL/eWgV0dCzhnPnTVXrWTsmhooy3s2TUcBxbdmQTbhvr3NMCRCTwsKA5xmb09poFPjaCtSIj4LB7rc8oe4KnbR6L0ARAozNGw1MFuGIxsG3r8pB3sf2xbwY3NLxMjmUFS6GJFWI5LPyxl/zI5C9ehI2djHGY3kKyd/ZI0Ov/nxbQpC/UHK14ZQfAPmgfpCCyYhH3r3brQ0mlybO42l9LzHWcss6J8kwibVJh1lGiT9kh/3Guk9WrN3+v6X9tf/EhbpZKOZBfYt5FJF05NDZZbsTEV6rattbdIUcFWY+nOKOrSo0sDTZdUQJE1gDpyZlS2iUg/Aon8WJUhvrVLEEKZxt98Zs0u1HbbKllCGvUMALkVDB1+mEic=
  email: false
