---
# tasks file for selinux
- name: include assert.yml
  include_tasks: assert.yml

- name: install required packages
  package:
    name: "{{ selinux_requirements }}"
    state: present
  register: selinux_install_required_packages
  until: selinux_install_required_packages is succeeded
  retries: 3

- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  notify:
    - reboot
  when:
    - ansible_selinux.status is defined
    - ansible_connection != "docker"
  register: selinux_manage_selinux
