---
# tasks file for selinux
- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy | default(omit) }}"
  when:
    - ansible_selinux.status is defined
    - ansible_virtualization_type != "docker"
  register: manage_selinux

- name: reboot for selinux
  include_role:
    name: robertdebock.reboot
  when:
    - manage_selinux.changed
  tags:
    - skip_ansible_lint
