---
# tasks file for selinux
- name: install required packages
  package:
    name: "{{ selinux_requirements }}"
    state: "{{ selinux_package_state }}"
  register: selinux_install_required_packages
  until: selinux_install_required_packages
  retries: 3

- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  when:
    - ansible_selinux.status is defined
    - ansible_virtualization_type != "docker" or selinux_ignore_docker
  register: manage_selinux

- name: reboot for selinux
  include_role:
    name: robertdebock.reboot
  when:
    - manage_selinux.changed
  tags:
    - skip_ansible_lint
